# Generated by Django 3.2.9 on 2021-11-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communautemodel',
            options={},
        ),
        migrations.AddField(
            model_name='communautemodel',
            name='membre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='communautemodel',
            name='type',
            field=models.CharField(choices=[('PU', 'Public'), ('PV', 'Prive'), ('RT', 'Restreint')], default='PU', max_length=2),
        ),
    ]
